# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

apiHost: "cargotracker-liberty-bff"

replicaCount: 1
logLevel: "debug"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 3000

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: false

ingress:
  enabled: true
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web
    binding:
      name: "binding-sandbox-team-one-appid"
      namespace: cargotracking-dev

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

vcsInfo:
  repoUrl: "https://github.com/tcs-sandbox-team-one/cargo-tracker-app.git"
  branch: "master"

partOf: "cargotracker-frontend-dev"

connectsTo: "cargotracker-org-bff"

runtime: js
